/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#00132d',
        surface: '#00132d',
        'surface-container': '#06203f',
        'surface-container-low': '#021c3a',
        'surface-container-lowest': '#000e24',
        'surface-container-high': '#132a4a',
        'surface-container-highest': '#1f3555',
        'surface-bright': '#243a5a',
        primary: '#81d4d8',
        'primary-container': '#0d7377',
        'primary-fixed': '#9df0f4',
        secondary: '#adccce',
        'secondary-container': '#314e4f',
        tertiary: '#ffb68e',
        'tertiary-container': '#975731',
        error: '#ffb4ab',
        'error-container': '#93000a',
        outline: '#889393',
        'outline-variant': '#3e4949',
        'on-surface': '#d5e3ff',
        'on-surface-variant': '#bec9c9',
        'on-primary': '#003739',
        'on-primary-container': '#a2f5f9',
        'on-secondary-container': '#9fbebf',
        'on-error-container': '#ffdad6',
        'deep-navy': '#0A2342',
        'teal-accent': '#0D7377',
        'aqi-good': '#14A44D',
        'aqi-moderate': '#EAB308',
        'aqi-poor': '#F97316',
        'aqi-critical': '#DC2626',
        'card-white': '#F8FAFC',
      },
      borderRadius: {
        'card': '16px',
        'button': '12px',
        'badge': '8px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        glow: '0 8px 24px rgba(13, 115, 119, 0.4)',
        ambient: '0 24px 48px rgba(0, 0, 0, 0.4)',
      },
    },
  },
  plugins: [],
}
